app_name: Kjuly.com
title: Kjuly
description: Products

# Products
YeNom_title: YeNom
YeNom_link: https://yenom.kjuly.com
Aidem_title: Aidem
Aidem_link: https://aidem-app.kjuly.com
Swing_title: Swing
Swing_link: https://swing.news

# true for dark theme, false to light theme, auto to switch with system.
dark-theme: auto

# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

keep_files: [
  "CNAME",
  "ads.txt",
]

exclude: [
  "*.code-workspace",
  "README.md",
  "Gemfile*",
  "Dockerfile*",
  "compose*.yaml",
  "*.sh",
  "sync_exclude.md",
]
