title: Kjuly
bio: Hi there, welcome to try my product.
description: Personal website.

# your site color theme, true for dark theme, 
# false to light theme, auto to switch with system.
dark-theme: auto

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jemoji

compress_html:
  ignore:
    envs:
      - development
      - stage

keep_files: [
  "CNAME",
  "ads.txt",
]

exclude: [
  "*.code-workspace",
  "README.md",
  "Gemfile*",
  "Dockerfile*",
  "compose*.yaml",
  "*.sh",
  "sync_exclude.md",
]
