name: ${APP_NAME}

services:
  jekyll:
    build: ${SOURCE_DIR}
    image: ghcr.io/kjulyx/env-kjuly-com:latest
    ports:
      - "8000:${CONTAINER_PORT}"
    working_dir: ${CONTAINER_WORK_DIR}
    volumes:
      - ${VOLUME_SOURCE}:${VOLUME_TARGET}
    command: bundle exec jekyll serve -H 0.0.0.0 -P ${CONTAINER_PORT} ${JEKYLL_CMD_EXTRA_OPTIONS}
