name: ${APP_NAME}

services:
  jekyll:
    build: ${SOURCE_DIR}
    image: ghcr.io/kjulyx/env-kjuly-com:latest
    working_dir: ${CONTAINER_WORK_DIR}
    volumes:
      - ${VOLUME_SOURCE}:${VOLUME_TARGET}
    command: bundle exec jekyll build
