app_name: Kjuly.cn
title: Kjuly
description: 开发日志与文档

# CN Version Specific
cn_icp_number: 浙ICP备2024093547号-1

# Products
YeNom_title: YeNom
YeNom_link: http://yenom.kjuly.cn
Aidem_title: Aidem
Aidem_link: http://aidem.kjuly.cn
